### ISSUE TITLE
Logging error in IMERG pipeline

### ISSUE THREAD

**Issue by hannahker** [OCHA-DAP/ds-raster-pipelines#58]
Doesn't seem to have any impact on functionality, but should clean this up:

```
2024-12-09 17:07:41 - IMERGPipeline - INFO - Running IMERG pipeline in prod mode...
2024-12-09 17:07:41 - IMERGPipeline - INFO - Retrieving IMERG data from 2024-12-08 to 2024-12-09...
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/databricks/python_shell/scripts/db_ipykernel_launcher.py", line 157, in <module>
    main()
  File "/databricks/python_shell/scripts/db_ipykernel_launcher.py", line 153, in main
    app.start()
  File "/databricks/python/lib/python3.10/site-packages/ipykernel/kernelapp.py", line 736, in start
    self.io_loop.start()
  File "/databricks/python/lib/python3.10/site-packages/tornado/platform/asyncio.py", line 199, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/databricks/python/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 516, in dispatch_queue
    await self.process_one()
  File "/databricks/python/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 505, in process_one
    await dispatch(*args)
  File "/databricks/python/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 412, in dispatch_shell
    await result
  File "/databricks/python/lib/python3.10/site-packages/ipykernel/kernelbase.py", line 740, in execute_request
    reply_content = await reply_content
  File "/databricks/python_shell/dbruntime/DatabricksShell.py", line 131, in do_execute
    reply_content = await super().do_execute(*args, **kwargs)
  File "/databricks/python/lib/python3.10/site-packages/ipykernel/ipkernel.py", line 422, in do_execute
    res = shell.run_cell(
  File "/databricks/python/lib/python3.10/site-packages/ipykernel/zmqshell.py", line 546, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/databricks/python/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3009, in run_cell
    result = self._run_cell(
  File "/databricks/python/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3064, in _run_cell
    result = runner(coro)
  File "/databricks/python/lib/python3.10/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/databricks/python/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3269, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/databricks/python/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3448, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/databricks/python/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/root/.ipykernel/1561/command--1-3553389868", line 8, in <module>
    exec(compile(f.read(), filename, 'exec'))
  File "/Workspace/Repos/.internal/5220b5ead7_commits/ffd0811a6bb32817a600603847dae0683002d602/run_pipeline.py", line 57, in <module>
    main()
  File "/Workspace/Repos/.internal/5220b5ead7_commits/ffd0811a6bb32817a600603847dae0683002d602/run_pipeline.py", line 49, in main
    run_imerg(base_parser)
  File "/Workspace/Repos/.internal/5220b5ead7_commits/ffd0811a6bb32817a600603847dae0683002d602/src/scripts/run_imerg_pipeline.py", line 72, in main
    pipeline.run_pipeline()
  File "/Workspace/Repos/.internal/5220b5ead7_commits/ffd0811a6bb32817a600603847dae0683002d602/src/pipelines/imerg_pipeline.py", line 131, in run_pipeline
    self._create_auth_files()
  File "/Workspace/Repos/.internal/5220b5ead7_commits/ffd0811a6bb32817a600603847dae0683002d602/src/pipelines/imerg_pipeline.py", line 115, in _create_auth_files
    self.logger.info("Saved .netrc, .urs_cookies, and .dodsrc to:", homeDir)
Message: 'Saved .netrc, .urs_cookies, and .dodsrc to:'
Arguments: ('/root/',)
2024-12-09 17:07:41 - IMERGPipeline - INFO - Getting data for 2024-12-08 00:00:00...
2024-12-09 17:07:41 - src.utils.azure_utils - WARNING - Blob imerg/daily/late/v7/raw/imerg-daily-late-2024-12-08.nc4 not found
2024-12-09 17:07:41 - IMERGPipeline - INFO - No cached data found. Querying API...
2024-12-09 17:07:41 - IMERGPipeline - INFO - Downloading data from 2024-12-08 00:00:00: imerg-daily-late-2024-12-08.nc4
2024-12-09 17:07:45 - src.utils.raster_utils - WARNING - Dataset was north down, latitude coordinates have been flipped
2024-12-09 17:07:46 - IMERGPipeline - WARNING - Input data is already a DataArray: 'DataArray' object has no attribute 'to_dataarray'
2024-12-09 17:07:55 - IMERGPipeline - INFO - Uploading processed data /tmp/tmppepinlqe/imerg/daily/late/v7/processed/imerg-daily-late-2024-12-08.tif to imerg/daily/late/v7/processed/imerg-daily-late-2024-12-08.tif
2024-12-09 17:07:56 - IMERGPipeline - INFO - Completed IMERG update.
2024-12-09 17:07:56 - IMERGPipeline - INFO - Cleaned up temporary directory: /tmp/tmppepinlqe
```

**Comment by hannahker** [comment]
Closed with #63
